# Generated by Django 5.2.2 on 2025-06-08 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('target_irr', models.DecimalField(blank=True, decimal_places=2, help_text='Target IRR in percent (e.g., 15.00 = 15%)', max_digits=5, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('transaction_type', models.CharField(choices=[('investment', 'Investment'), ('return', 'Return')], max_length=20)),
                ('investment', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('return_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('equity', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('cash_flow', models.DecimalField(decimal_places=2, max_digits=20)),
                ('nav', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='investments.project')),
            ],
        ),
    ]
