# Generated by Django 5.2.2 on 2025-06-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_alter_project_target_irr_alter_transaction_cash_flow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='x_rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='X-Rate (Currency)'),
        ),
    ]
