# Generated by Django 5.2.2 on 2025-06-10 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_transaction_x_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='hash',
            field=models.CharField(blank=True, help_text='Unique hash for identifying duplicate transactions', max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='currency',
            field=models.CharField(default='USD', help_text='Currency of the project (e.g. USD, EUR)', max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='target_irr',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Target IRR (%) expected for this project', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='cash_flow',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Auto-calculated net cash flow based on investment, return, or NAV.', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(help_text='Date of the transaction (investment, return, or NAV update).'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='equity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Latest known equity value, used for TVPI calculation.', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='investment',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Investment amount (positive number). Leave blank if not applicable.', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='nav',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Net Asset Value (NAV) at the transaction date, used for XIRR if no return.', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='return_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Return amount (positive number). Leave blank if not applicable.', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('investment', 'Investment'), ('return', 'Return')], help_text='Type of transaction: investment or return.', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='x_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Exchange rate to USD at the time of transaction (e.g., EUR/USD).', max_digits=10, null=True),
        ),
    ]
