# Generated by Django 5.2.2 on 2025-06-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0004_transaction_hash_alter_project_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='cash_flow',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='hash',
        ),
        migrations.AddField(
            model_name='project',
            name='dpi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='estimated_return',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='gap_to_target',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='invested',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='irr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='returned',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='tvpi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='xnpv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(default='Active', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='target_irr',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='equity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='investment',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='nav',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='return_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('investment', 'Investment'), ('return', 'Return')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='x_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
