# Generated by Django 5.2.2 on 2025-06-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0005_remove_project_currency_remove_transaction_cash_flow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='nav',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
