# Generated by Django 5.2.2 on 2025-06-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0008_alter_transaction_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Investment', 'Investment'), ('Return', 'Return')], max_length=20),
        ),
    ]
