# Generated by Django 5.2.2 on 2025-06-24 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0009_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='equity',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
