# Generated by Django 5.2.2 on 2025-07-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0010_alter_transaction_equity'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='moic',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='moic_source',
            field=models.CharField(blank=True, choices=[('provided', 'Provided'), ('calculated', 'Calculated')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=10),
        ),
    ]
