# Generated by Django 4.2.23 on 2025-08-10 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0011_project_moic_project_moic_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Main Portfolio', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mirr_finance_rate', models.FloatField(default=0.1, help_text='Finance rate for portfolio mIRR calculation (0.10 = 10%)')),
                ('mirr_reinvest_rate', models.FloatField(default=0.12, help_text='Reinvestment rate for portfolio mIRR calculation (0.12 = 12%)')),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolios',
            },
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='equity',
            field=models.FloatField(blank=True, editable=False, help_text='Накопленная equity', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='investment',
            field=models.FloatField(blank=True, help_text='Сумма инвестиции', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='nav',
            field=models.FloatField(blank=True, help_text='Net Asset Value', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='return_amount',
            field=models.FloatField(blank=True, help_text='Сумма возврата', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='x_rate',
            field=models.FloatField(blank=True, default=1.0, help_text='Курс валют', null=True),
        ),
    ]
